### ISSUE TITLE
Fails when following Readme Setup instructions

### ISSUE THREAD

**Issue by kristianmandrup** [angular/projects#7]
## Setup
1. Install [NodeJS](http://nodejs.org/)
2. `npm install -g gulp`
3. `npm install -g bower`
4. `npm install -g protractor`
5. `npm install`
6. `bower install`
## Running the Samples
1. `gulp build watch serve`
2. open [http://localhost:8000/](http://localhost:8000/)

``` js
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8000/lib/router/index.js
Error: Script error for: libPath/router/index
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://localhost:8000/lib/require.js:166:17)
    at HTMLScriptElement.context.onScriptError (http://localhost:8000/lib/require.js:1689:36)
    at Zone.run (http://localhost:8000/lib/zone.js:87:19)
    at HTMLScriptElement.zoneBoundFn (http://localhost:8000/lib/zone.js:64:19) bootstrap.js:54
GET http://localhost:8000/lib/platform.js.map 404 (Not Found) 
```

When I look in the `dist` folder I notice the following:

`lib/router` only has a `router-directive.js` file, not an `index.js` file, so no wonder I get a 404.
The file `lib/platform.js.map` is also not present, only the `lib/platform.js`. 

Please fix the setup guide. Thanks :)

**Comment by heycalmdown** [comment]
:+1:

**Comment by ItsBenCodes** [comment]
:+1:

**Comment by tommymcdonald** [comment]
:+1:
